services:
    mysql:
        image: mysql:8.0
        container_name: internship_db
        # restart: always
        ports:
            - "3333:3306" # expose port
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: internship-tutorial
            MYSQL_USER: intern
            MYSQL_PASSWORD: 12345678
        volumes:
            - mysql_data2:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: internship_redis
        ports:
            - "6379:6379"
volumes:
    mysql_data2:
